# This file was autogenerated by android-configure.sh. Do not edit !
HOST_OS     := linux
HOST_ARCH   := x86
HOST_CC     := objs/toolchain/x86_64-linux-gcc
HOST_CXX    := objs/toolchain/x86_64-linux-g++
HOST_LD     := objs/toolchain/x86_64-linux-g++
HOST_AR     := objs/toolchain/x86_64-linux-ar
HOST_WINDRES:= 
OBJS_DIR    := objs

HOST_PREBUILT_TAG := linux-x86
HOST_EXEEXT       := 
HOST_DLLEXT       := .so
PREBUILT          := 
PREBUILTS         := 

BUILD_EXEEXT      := 
BUILD_DLLEXT      := 
BUILD_AR          := objs/toolchain/x86_64-linux-ar
BUILD_CC          := objs/toolchain/x86_64-linux-gcc
BUILD_CXX         := objs/toolchain/x86_64-linux-g++
BUILD_LD          := objs/toolchain/x86_64-linux-g++
BUILD_CFLAGS      :=  -m32
BUILD_LDFLAGS     :=  -m32
SRC_PATH          := /home/developer/android_source/external/droidscope
CONFIG_COREAUDIO  := no
CONFIG_WINAUDIO   := no
CONFIG_ESD        := yes
CONFIG_ALSA       := yes
CONFIG_OSS        := yes
CONFIG_PULSEAUDIO := yes
EMULATOR_USE_SDL2 := true
EMULATOR_USE_QT   := false
EMULATOR_BUILD_EMUGL       := true
EMULATOR_EMUGL_SOURCES_DIR := distrib/android-emugl
#undef CONFIG_QT
