// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __gles1_server_context_t_h
#define __gles1_server_context_t_h

#include "gles1_server_base.h"


struct gles1_server_context_t : gles1_server_base_t {

	 virtual ~gles1_server_context_t() {}
	int initDispatchByName( void *(*getProc)(const char *name, void *userData), void *userData);
};

#endif
