# Automatically generated by configure - do not modify
TARGET_DIR=objs
TARGET_CONFIG_MAKE=config.make
TARGET_ARCH=arm
TARGET_CFLAGS=-I$(SRC_PATH)/android/config/target-$(TARGET_ARCH)
SRC_PATH=/home/yduan/yueduan/android-5.0.0_r3/external/droidscope_art_alternate
PLUGIN_PATH=/home/yduan/yueduan/android-5.0.0_r3/external/droidscope_art_alternate/DECAF_plugins/old_dex_extarctor
