// Generated Code - DO NOT EDIT !!
// generated by 'emugen'

#ifndef GUARD_gles2_decoder_context_t
#define GUARD_gles2_decoder_context_t

#include "IOStream.h" 
#include "gles2_server_context.h"



struct gles2_decoder_context_t : public gles2_server_context_t {

	size_t decode(void *buf, size_t bufsize, IOStream *stream);

};

#endif  // GUARD_gles2_decoder_context_t
