// Generated Code - DO NOT EDIT !!
// generated by 'emugen'
#ifndef __gles2_server_context_t_h
#define __gles2_server_context_t_h

#include "gles2_server_base.h"


struct gles2_server_context_t : gles2_server_base_t {

	 virtual ~gles2_server_context_t() {}
	int initDispatchByName( void *(*getProc)(const char *name, void *userData), void *userData);
};

#endif
