# Automatically generated by configure - do not modify
TARGET_DIR=objs
TARGET_CONFIG_MAKE=config.make
TARGET_ARCH=arm
TARGET_CFLAGS=-I$(SRC_PATH)/android/config/target-$(TARGET_ARCH)
SRC_PATH=/home/zhenxiao/source/external/droidscope
PLUGIN_PATH=/home/zhenxiao/source/external/droidscope/DECAF_plugins/old_dex_extarctor
